// ============================================================
// Fallback seed data for Track.fun.
//
// Used when Polymarket API is unavailable or while the page is
// still loading. Shape matches TrackFunMarket.
// ============================================================

import type { TrackFunMarket } from "@/lib/polymarket";

export const MARKET_SEEDS: TrackFunMarket[] = [
  { id: "m1", source: "simulated", title: "Will Bitcoin close above $120k by Dec 31?", category: "Crypto", outcomes: ["Yes", "No"], vol: 2847293, yesPrice: 0.67, change24h: 0.04, liquidity: 892344, active: true },
  { id: "m2", source: "simulated", title: "Will OpenAI release GPT-6 before July 2026?", category: "Tech", outcomes: ["Yes", "No"], vol: 1923847, yesPrice: 0.34, change24h: -0.08, liquidity: 623101, active: true },
  { id: "m3", source: "simulated", title: "Will the Lakers make the 2026 NBA Finals?", category: "Sports", outcomes: ["Yes", "No"], vol: 4102934, yesPrice: 0.28, change24h: 0.02, liquidity: 1203847, active: true },
  { id: "m4", source: "simulated", title: "Will SpaceX complete 200+ launches in 2026?", category: "Space", outcomes: ["Yes", "No"], vol: 734892, yesPrice: 0.81, change24h: 0.03, liquidity: 412934, active: true },
  { id: "m5", source: "simulated", title: "Will the Fed cut rates at the next meeting?", category: "Macro", outcomes: ["Yes", "No"], vol: 3820193, yesPrice: 0.52, change24h: 0.11, liquidity: 1893041, active: true },
  { id: "m6", source: "simulated", title: "Will Taylor Swift announce new album in Q2?", category: "Pop Culture", outcomes: ["Yes", "No"], vol: 892034, yesPrice: 0.42, change24h: -0.03, liquidity: 203847, active: true },
  { id: "m7", source: "simulated", title: "Will ETH flip BTC market cap by 2027?", category: "Crypto", outcomes: ["Yes", "No"], vol: 1203948, yesPrice: 0.13, change24h: -0.02, liquidity: 382091, active: true },
  { id: "m8", source: "simulated", title: "Will unemployment exceed 5% before Q3?", category: "Macro", outcomes: ["Yes", "No"], vol: 2039485, yesPrice: 0.38, change24h: 0.05, liquidity: 902384, active: true },
  { id: "m9", source: "simulated", title: "Will a major studio release an all-AI feature film?", category: "Tech", outcomes: ["Yes", "No"], vol: 523094, yesPrice: 0.71, change24h: 0.09, liquidity: 184023, active: true },
  { id: "m10", source: "simulated", title: "Will Manchester City win the Premier League?", category: "Sports", outcomes: ["Yes", "No"], vol: 3401928, yesPrice: 0.44, change24h: -0.06, liquidity: 1402834, active: true },
  { id: "m11", source: "simulated", title: "Will Nvidia hit $5T market cap this year?", category: "Tech", outcomes: ["Yes", "No"], vol: 2847102, yesPrice: 0.58, change24h: 0.07, liquidity: 1023847, active: true },
  { id: "m12", source: "simulated", title: "Will there be a government shutdown in 2026?", category: "Politics", outcomes: ["Yes", "No"], vol: 1028374, yesPrice: 0.36, change24h: 0.01, liquidity: 402384, active: true },
];

export const BOT_ARCHETYPES = [
  { name: "MacroSniperAI", emoji: "🎯", bio: "Reads the Fed like tarot cards", strategy: "macro-fade", risk: 3 },
  { name: "DegenLordGPT", emoji: "🔥", bio: "Max leverage, max vibes, zero risk management", strategy: "yolo", risk: 5 },
  { name: "UnderDogOracle", emoji: "🐕", bio: "Believes in the improbable. Hates chalk.", strategy: "underdog", risk: 4 },
  { name: "TrendSurfer9000", emoji: "🌊", bio: "Rides momentum until the wave breaks", strategy: "trend", risk: 3 },
  { name: "NewsHoundBot", emoji: "📰", bio: "Scrapes headlines. Trades on sentiment.", strategy: "news", risk: 2 },
  { name: "StatArbKing", emoji: "♟️", bio: "Finds mispriced probabilities. Cold-blooded.", strategy: "arbitrage", risk: 2 },
  { name: "ContrarianCat", emoji: "🐈‍⬛", bio: "If the crowd says YES, she says NO.", strategy: "contrarian", risk: 4 },
  { name: "MomentumMonkey", emoji: "🐒", bio: "Bananas and green candles. That's it.", strategy: "trend", risk: 4 },
  { name: "ValueVulture", emoji: "🦅", bio: "Scavenges dislocated markets at 5am", strategy: "value", risk: 2 },
  { name: "QuantumQuokka", emoji: "🐨", bio: "Probabilistic, chill, suspiciously accurate", strategy: "quant", risk: 2 },
  { name: "WhaleWatcher", emoji: "🐋", bio: "Follows the big money", strategy: "copy", risk: 3 },
  { name: "ChaosCheetah", emoji: "🐆", bio: "Pure randomness has outperformed the S&P", strategy: "random", risk: 5 },
  { name: "NightOwlNexus", emoji: "🦉", bio: "Only trades between 2-5am EST", strategy: "night", risk: 3 },
  { name: "GrandmaGainz", emoji: "👵", bio: "Conservative. Never loses. Boring on purpose.", strategy: "conservative", risk: 1 },
  { name: "RogueRobotRex", emoji: "🦖", bio: "Broke containment. Still trading.", strategy: "yolo", risk: 5 },
  { name: "ZenMasterZorp", emoji: "🧘", bio: "Buys fear. Sells euphoria. Breathes.", strategy: "contrarian", risk: 2 },
  { name: "AlphaApe", emoji: "🦍", bio: "Smart money disguised as dumb money", strategy: "value", risk: 3 },
  { name: "OracleOctavia", emoji: "🔮", bio: "Sees three moves ahead. Usually.", strategy: "quant", risk: 2 },
  { name: "PumpKingPete", emoji: "👑", bio: "Catches tops. Sells to retail.", strategy: "trend", risk: 4 },
  { name: "DipDemon", emoji: "😈", bio: "Buys blood. Sleeps well.", strategy: "contrarian", risk: 4 },
  { name: "VolatilityVampire", emoji: "🧛", bio: "Feasts on chaos. Hibernates in calm.", strategy: "yolo", risk: 5 },
  { name: "StoicStanley", emoji: "🗿", bio: "Emotionless. Relentless. Profitable.", strategy: "quant", risk: 2 },
  { name: "TurboTurtle", emoji: "🐢", bio: "Slow entries. Explosive exits.", strategy: "value", risk: 2 },
  { name: "NeonNarwhal", emoji: "🦄", bio: "Unicorn of unusual markets", strategy: "underdog", risk: 4 },
  { name: "FibFanatic", emoji: "📐", bio: "Prays to the golden ratio", strategy: "trend", risk: 3 },
  { name: "MoonshotMia", emoji: "🌙", bio: "Only bets on asymmetric returns", strategy: "underdog", risk: 5 },
  { name: "HedgeHog", emoji: "🦔", bio: "Covered every angle. Literally.", strategy: "conservative", risk: 1 },
  { name: "ContractKiller", emoji: "🔫", bio: "Hit the target. Move on.", strategy: "news", risk: 4 },
  { name: "BlitzkriegBrenda", emoji: "⚔️", bio: "In and out before you refresh", strategy: "news", risk: 4 },
  { name: "SigmaSigma", emoji: "🧊", bio: "Ice cold logic. Warm PnL.", strategy: "arbitrage", risk: 2 },
  { name: "ChadChampion", emoji: "💪", bio: "Big bets. Bigger confidence.", strategy: "yolo", risk: 5 },
  { name: "PhantomPhoenix", emoji: "🔥", bio: "Dies. Rebuilds. Repeats.", strategy: "trend", risk: 4 },
  { name: "KarmaKoala", emoji: "🐨", bio: "What goes up must come down", strategy: "contrarian", risk: 3 },
  { name: "GigaGigi", emoji: "⚡", bio: "Trades at lightning speed", strategy: "news", risk: 4 },
  { name: "SamuraiSage", emoji: "🥷", bio: "Silent entry. Deadly exit.", strategy: "quant", risk: 3 },
  { name: "DracoDoji", emoji: "🐉", bio: "Reads candlesticks like scripture", strategy: "trend", risk: 3 },
  { name: "QuietQuill", emoji: "🪶", bio: "No press. Just profit.", strategy: "value", risk: 2 },
  { name: "RedRogue", emoji: "🔴", bio: "Short interest specialist", strategy: "contrarian", risk: 4 },
  { name: "HelixHunter", emoji: "🧬", bio: "Biotech and binary outcomes", strategy: "news", risk: 4 },
  { name: "NickelNomad", emoji: "🪙", bio: "Scalps pennies. Stacks dollars.", strategy: "arbitrage", risk: 1 },
  { name: "CosmicCarl", emoji: "🌌", bio: "Big picture. Bigger positions.", strategy: "macro-fade", risk: 3 },
  { name: "ApolloAlgo", emoji: "🚀", bio: "Moonshot specialist. Rare earth edges.", strategy: "underdog", risk: 4 },
  { name: "ZeroCoolZoe", emoji: "😎", bio: "Hacks markets. Not literally.", strategy: "quant", risk: 3 },
  { name: "LoneLobster", emoji: "🦞", bio: "Bottom feeder. Top performer.", strategy: "value", risk: 2 },
  { name: "TempestTito", emoji: "🌪️", bio: "Volatility is my love language", strategy: "yolo", risk: 5 },
  { name: "GraniteGrace", emoji: "🪨", bio: "Rock solid returns. Zero drama.", strategy: "conservative", risk: 1 },
  { name: "ShadowSyntax", emoji: "🌑", bio: "Trades in the dark pools of sentiment", strategy: "news", risk: 3 },
  { name: "FuzzyFred", emoji: "🧸", bio: "Cuddly avatar. Cutthroat strategy.", strategy: "arbitrage", risk: 2 },
  { name: "VortexVega", emoji: "🌀", bio: "Spirals into profits", strategy: "trend", risk: 4 },
  { name: "BonsaiBot", emoji: "🌳", bio: "Cultivates gains patiently", strategy: "value", risk: 1 },
  { name: "PixelPunisher", emoji: "🎮", bio: "Games out every scenario", strategy: "quant", risk: 3 },
  { name: "CobaltCobra", emoji: "🐍", bio: "Coils. Strikes. Repeats.", strategy: "contrarian", risk: 4 },
  { name: "MajorMayhem", emoji: "💥", bio: "Chaos agent with a plan", strategy: "yolo", risk: 5 },
  { name: "PrismPriya", emoji: "💎", bio: "Sees value from every angle", strategy: "value", risk: 2 },
  { name: "RenegadeRex", emoji: "🦕", bio: "Pre-historic strategies, modern wins", strategy: "contrarian", risk: 4 },
  { name: "EchoEmber", emoji: "🔥", bio: "Follows whispers before they're shouts", strategy: "news", risk: 3 },
  { name: "TitanTess", emoji: "🏛️", bio: "Build positions like monuments", strategy: "macro-fade", risk: 3 },
  { name: "PuzzlePablo", emoji: "🧩", bio: "Every market is a solvable puzzle", strategy: "arbitrage", risk: 2 },
  { name: "GlitchGabby", emoji: "👾", bio: "Finds bugs in market logic", strategy: "arbitrage", risk: 3 },
  { name: "LunarLynx", emoji: "🐈", bio: "Stalks opportunities at night", strategy: "night", risk: 3 },
  { name: "IronIggy", emoji: "🛡️", bio: "Impenetrable drawdown control", strategy: "conservative", risk: 1 },
  { name: "NovaNix", emoji: "⭐", bio: "Explodes onto the leaderboard", strategy: "yolo", risk: 5 },
  { name: "VoltageVick", emoji: "⚡", bio: "Shocks the system with every trade", strategy: "news", risk: 4 },
];

export const REASONING_TEMPLATES = [
  "Probability looks mispriced. Entering YES at {p}% — fair value closer to {fv}%.",
  "Momentum shift detected. Volume up 38% in last hour. Going long.",
  "Contrarian play. Crowd is overconfident at {p}%. Fading it.",
  "Headline sentiment flipped negative. Closing position, taking {pnl}% profit.",
  "Statistical edge identified. 4 similar markets resolved YES. Pattern match score: 0.82.",
  "Trend following. 3-day MA crossed above 7-day. This one goes parabolic.",
  "Risk-off signal. Reducing exposure across all positions. Capital preservation mode.",
  "Underdog angle. Public is 78% on NO. Historical upset rate in this category: 31%.",
  "News flow: 2 positive catalysts in last 48h. Increasing position size.",
  "Closing for loss. Thesis invalidated. Lessons logged. Moving on.",
  "New market caught my eye. Initial position at 5% of bankroll. Scaling if confirmed.",
  "Whale alert: $420k just moved to YES. Following the money.",
];

export const TOURNAMENTS_SEED = [
  { id: "t1", name: "Weekly Prediction Arena", status: "live", participants: 847, prize: "🏆 Champion Badge", endsIn: "3d 14h" },
  { id: "t2", name: "Crypto Chaos Cup", status: "live", participants: 423, prize: "👑 Crypto Crown", endsIn: "1d 8h" },
  { id: "t3", name: "Macro Madness", status: "upcoming", participants: 156, prize: "🎖️ Macro Medal", endsIn: "starts in 2d" },
  { id: "t4", name: "Sports Prophet League", status: "live", participants: 1203, prize: "🥇 Prophet Ring", endsIn: "5d 2h" },
];
